### ISSUE TITLE
Xenko and statics

### ISSUE THREAD

**Issue by Eideren** [xenko3d/xenko#180]
Does Xenko need [ScriptComponents](https://github.com/xenko3d/xenko/blob/master/sources/engine/Xenko.Engine/Engine/ScriptComponent.cs) to have all of those objects provided as instances instead of having them as statics instead, I'm thinking of the InputManager, Game, and others which are more often than not instantiated only once ?

I'm asking this because I'm porting working networking code from unity to xenko and need components to be as lightweight as possible to serialize and synchronize them efficiently.

It's not a request, I'll do it on my branch, but would prefer knowing before hand if I'm actually digging my own grave here.

I understand that in certain cases it might be useful to have multiple instances of Game (et al.) running but in my case its just more of a headache.

**Comment by xen2** [comment]
Yes the idea is to not end up having global objects, to make Xenko more usable in advanced scenarios (hosted inside editor, multiple game at same time, mockups/unit tests, plug a fake input system to emulate something, etc...).
The few singletons we still had (i.e. recently removed `ContentManager.FileProvider`) all proved to end up bring lot of issues/headaches.

However, I agree it could be useful for some games, and nothing prevent users to have something it if it fits their specific case (i.e. make a `Global` class which host all the static systems, initialized at game startup).

**Comment by xen2** [comment]
BTW, since you mentioned your concern is components being lightweights, those are not serialized and just provided for easier access (of course it costs a few pointers).
If size of Entity component is your concern, it might make sense to create a shared object that contains all of them (it doesn't need to be static though, just shared and easily accessible by all scripts). It's probably something that the user might want to extend to add easy access to his own subsystem or anything that's not part of Xenko core (esp. if we want to be plugin friendly).

**Comment by Eideren** [comment]
Alright, thanks a whole bunch for the clarification !
