### ISSUE TITLE
Shader files can't reference each other when placed in different folders

### ISSUE THREAD

**Issue by tebjan** [xenko3d/xenko#212]
**Release Type**:
Official

**Version**:
3.0.0.5

**Platform(s)**:
Windows, Shared

**Describe the bug**
Shader .xksl files cannot reference each other.

**To Reproduce**
1. Create new game project
2. Add several .xksl files in visual studio in different folders
3. Inherit from shader B in shader A in a different folder in the same .csproj project

Demo game project: https://github.com/tebjan/Xenko.LocalShaderReferences/releases/

**Expected behavior**
Shaders can reference each other

**Screenshots**
![image](https://user-images.githubusercontent.com/1094716/45911985-f5f98e00-be1a-11e8-8f58-e500ce0204a4.png)

![image](https://user-images.githubusercontent.com/1094716/45888316-0a5b6d80-bdbe-11e8-8164-247b0c4c9406.png)

**Log and callstacks**
The class [BaseShader] was not found in the include path

**Comment by xen2** [comment]
@tebjan to clarify, is this only a Visual Studio design-time issue, or it also fails at runtime when using this `Feature1Shaders`?

**Comment by tebjan** [comment]
@xen2 yes, that is indeed the case. the shader compiler seems to pick it up correctly, only the system that manages the visual studio error reporting doesn't seem to pick up the files:

![image](https://user-images.githubusercontent.com/1094716/46099454-1c2a7f80-c1c7-11e8-826e-8ec81d37fd05.png)

![image](https://user-images.githubusercontent.com/1094716/46099422-0a48dc80-c1c7-11e8-834d-85f7340b0e1a.png)

![image](https://user-images.githubusercontent.com/1094716/46099400-fd2bed80-c1c6-11e8-8064-e44b4c06fa79.png)

**Comment by xwellingtonx** [comment]
The bug is because the file directory is to added and not solution directory what causes an file not found exception for inheritances in another folders.

https://github.com/xenko3d/xenko/blob/d8961d3d8a09f330c8fb018d160e643afd58555b/sources/tools/Xenko.VisualStudio.Commands/XenkoCommands.cs#L49-L56

@xen2, @Kryptos-FR, Some idea how is possible to list all folders on a solution or another way of to fix this issue?

**Comment by tebjan** [comment]
@xwellingtonx thank you for investigating on this. maybe there is an easy fix for that.

**Comment by xen2** [comment]
I see, thanks for investigating.
What it should do is use the game package assets. Right now it lists Assets from Xenko package (Xenko.xkpkg) but not from the user package (i.e. MyGame.xkpkg).

What might be worth investigating is, do we have enough info at that point to know the user package filepath?
If yes, we could simply load it by passing its path as `CollectShadersDirectories` parameter rather than just loading Xenko package.

**Comment by xwellingtonx** [comment]
@xen2, We haven't a way to get the user package for now the only way It's to find the package when the `XenkoCommandsProxy` it's initialize because there we have the solution file path. Do we have some way to get the user package inside a solution file?

Remembering that to be done it will be necessary to create another class of `IXenkoCommands` because of the backwards compatibility.

https://github.com/xenko3d/xenko/blob/d9a3ba88140c1bf2c9b3f6c0be4a9d2b76d1a8b7/sources/tools/Xenko.VisualStudio.Package/Commands/IXenkoCommands.cs#L10-L41

**Comment by xen2** [comment]
@xwellingtonx yes, no problem to add a `IXenkoCommands2` and check if type implement interface before calling it.
Ideally it should work at project level rather than solution (a solution might contain multiple packages and the shaders could be unrelated). Not sure if we can access document=>project info from `AnalyzeAndGoToDefinition` though.

**Comment by xwellingtonx** [comment]
@xen2 I see...
The xkpkg file is only one per solution right? because what I thought could works with the solution was to just get the xkpkg reference inside it.
```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "LocalShaderReferences", "LocalShaderReferences", "{97ECFB22-8B7E-4DCF-82F6-CCBA8200AA48}"
	ProjectSection(XenkoPackage) = preProject
		LocalShaderReferences/LocalShaderReferences.xkpkg = LocalShaderReferences/LocalShaderReferences.xkpkg
	EndProjectSection
EndProject
```

And after get de assets folder inside xkpkg file.
```
        AssetFolders:
            -   Path: Assets/Shared
            -   Path: LocalShaderReferences.Game/Effects
            -   Path: LocalShaderReferences.Game/Shaders
```

**Comment by xen2** [comment]
@xwellingtonx actually I am doing some changes in the VSPackage system with 3.1 (xkpkg are now located/found in a different way).
As a result let's revisit this issue once those changes are merged in and do the fix directly in 3.1 branch.

**Comment by xwellingtonx** [comment]
@xen2, I think it's the better! Feel free to fix it while you change the VSPackage system if will be easy and fast if not we to fix it after.

**Comment by tebjan** [comment]
just opened this project and upgraded to latest xenko beta, the error seems to be gone. will re-open if it happens again.
