### ISSUE TITLE
Windows Defender now detects Trojan:Win32/Zpevdo.B in Xenko.exe

### ISSUE THREAD

**Issue by justStand** [xenko3d/xenko#285]
![image](https://user-images.githubusercontent.com/6134159/49489408-a44c8700-f7ff-11e8-9516-221e415d727c.png)

**Comment by Kryptos-FR** [comment]
I recently add it as a false positive for manually compiled version. Mainly because in that case assemblies and executables were not signed.

Never happened for the first installation of Xenko, but could after an update (because not everything was signed in the nuget package). Was it a new installation or an update in your case?

In the latter case, should be fixed by f6761691c7a6234d7cc9b216fa2719d174ebad7e and f6761691c7a6234d7cc9b216fa2719d174ebad7e. @xen2 would it be possible to cherry-pick those and release a new version?

**Comment by xen2** [comment]
New launcher (3.0.x) should not have this problem anymore.
Please reopen if it happens again.
